### PR TITLE
Colors are now much closer to one dark

### PR DESCRIPTION
**Pull request by shubhamgupta731**
Got the exact hash color codes using inspect elements in the one dark scheme in atom

### CODE REVIEW

**Comment by geoffharcourt** [comment]
Awesome! Quick question: are you using 24-bit (true) color in your editor? In my first go at this, I had to make some compromises on color choices.

**Comment by shubhamgupta731** [comment]
Yeah I am using neovim which supports 24 bit colors. But it also looks good in vim and works perfectly in macVim.

**Comment by shubhamgupta731** [comment]
I have updated the file a bit so that we define constants for different colors as one dark has singular color codes for all different colors.

**Comment by geoffharcourt** [comment]
Thank you for the improvements!

**Comment by shubhamgupta731** [comment]
Cool thanks

**Pull request merged**
