### PR TITLE
Airline theme

### PR DESCRIPTION
**Pull request by ahmedelgabri**
This is a very minimal airline theme for one-dark.

### CODE REVIEW

**Comment by geoffharcourt** [comment]
Cool! I want to test this out a bit before merging, but very excited about this addition.

**Comment by ahmedelgabri** [comment]
Take your time, It's my first Airline theme and I did it in like 40mins or so. I tired to keep it as simple as possible but maybe you have better ideas.

**Comment by geoffharcourt** [comment]
I use airline and the idea of doing this here hadn't even occurred to me!

**Comment by ahmedelgabri** [comment]
I was going to create a PR directly to the airline repo but then I remembered that some themes come with their own airline themes like [`gruvbox`](https://github.com/morhetz/gruvbox) then I found the info needed in the airline [FAQ](https://github.com/bling/vim-airline/wiki/FAQ#where-should-i-store-my-own-custom-theme) and I thought it'll make sense to add it here

**Comment by geoffharcourt** [comment]
@ahmedelgabri does this cause errors if the user does not have airline.vim installed?

**Comment by ahmedelgabri** [comment]
I don't think so. Because lots of themes seems to have airline themes that comes with them. 
But I'll test and remove airline and see what will happen. 

Sent from my iPhone

On Fri, Jan 8, 2016 at 10:05 AM -0800, "Geoff Harcourt" notifications@github.com wrote:

@ahmedelgabri does this cause errors if the user does not have airline.vim installed?

**Comment by geoffharcourt** [comment]
If that's GTG, let me know and I will merge. Thank you!

**Comment by ahmedelgabri** [comment]
@geoffharcourt I removed Airline and it just fell back to the default Vim statusline, no errors or anything. I also tried `gruvbox` which comes with an airline theme too and all is fine.

**Comment by geoffharcourt** [comment]
Thanks @ahmedelgabri!

**Comment by ahmedelgabri** [comment]
You are welcome :blush:

**Pull request merged**
